

###
GET http://10.221.154.185:9003/shopping2
Accept: application/json

###
PUT http://10.221.154.185:9003/shopping2
Accept: application/json

###



###
GET http://10.221.154.185:9003/_cat/indices?v
Accept: application/json

###

POST http://10.221.154.185:9003/shopping2
Accept: application/json

###
DELETE http://10.221.154.185:9003/shopping2
Accept: application/json

###

###

POST http://10.221.154.185:9003/shopping/_doc
Accept: application/json
Content-Type: application/json


{
  "name": "nancy",
  "sex": "女",
  "age": "22",
  "image": "beauty"
}

###

PUT http://10.221.154.185:9003/shopping/_doc
Accept: application/json
Content-Type: application/json


{
  "name": "nancy",
  "sex": "女",
  "age": "22",
  "image": "beauty"
}


###
POST http://10.221.154.185:9003/shopping/_doc/1001
Accept: application/json
Content-Type: application/json


{
  "name": "tom",
  "sex": "cat",
  "age": "13",
  "image": "beautiful"
}



###

PUT http://10.221.154.185:9003/shopping/_doc/1002
Accept: application/json
Content-Type: application/json


{
  "name": "tom",
  "sex": "cat",
  "age": "13",
  "image": "beautiful"
}




###
GET http://10.221.154.185:9003/shopping/_doc/1001
Accept: application/json
Content-Type: application/json


{
  "name": "tom",
  "sex": "cat",
  "age": "13",
  "image": "beautiful"
}


###
GET http://10.221.154.185:9003/shopping/_doc/2001
Accept: application/json
Content-Type: application/json


{
  "name": "tom",
  "sex": "cat",
  "age": "13",
  "image": "beautiful"
}


###
GET http://10.221.154.185:9003/shopping/_search
Accept: application/json
Content-Type: application/json


{
}



###
PUT http://10.221.154.185:9003/shopping/_doc/1001
Accept: application/json
Content-Type: application/json


{
  "name": "jerry",
  "sex": "mouse",
  "age": "09",
  "image": "funny"
}

###
POST http://10.221.154.185:9003/shopping/_update/1001
Accept: application/json
Content-Type: application/json


{
  "doc": {
    "name": "jerry2"
  }
}


###
DELETE http://10.221.154.185:9003/shopping/_doc/1001
Accept: application/json
Content-Type: application/json



###
GET http://10.221.154.185:9003/shopping/_search?q=sex:cat
Accept: application/json
Content-Type: application/json


{
}

###
GET http://10.221.154.185:9003/shopping/_search
Accept: application/json
Content-Type: application/json


{
  "query": {
    "match": {
      "sex": "cat"
    }
  }
}

###
GET http://10.221.154.185:9003/shopping/_search
Accept: application/json
Content-Type: application/json


{
  "query": {
    "match_all": {
    }
  }
}

### 分页查询
GET http://10.221.154.185:9003/shopping/_search
Accept: application/json
Content-Type: application/json


{
  "query": {
    "match_all": {
    }
  },
  "from": 0,
  "size": 2
}

### 分页查询,指定数据源
GET http://10.221.154.185:9003/shopping/_search
Accept: application/json
Content-Type: application/json


{
  "query": {
    "match_all": {
    }
  },
  "from": 0,
  "size": 2,
  "_source": [
    "name","age"
  ]
  ,
  "sort": {
    "age": {
      "order": "desc"
    }
  }
}
